export const TableData = {
  tableHeader: [
    "Bettor",
    "Email-Mobile",
    "Country",
    "Joined At",
    "Balance",
    "Action",
  ],
  pageNo: 1,
  totalPages: 100,
  tableRows: [],
};

// Helper function to generate random data
function generateRandomData(numEntries) {
  const names = [
    "John Doe",
    "Sarah Lee",
    "Ahmed Amin",
    "Chen Zhang",
    "Yasmin Cohen",
    "Liam O'Reilly",
    "Marta Lopez",
    "Sergey Ivanov",
    "Yuki Takahashi",
    "Rachel Bloom",
    "Mohammed Al-Farhan",
    "Anika Mehta",
    "David King",
    "Javier Gonzalez",
    "Sofia Rossi",
    "Amir Levi",
    "Emily Stone",
    "Carlos Hernandez",
    "Ariella Green",
    "Jacob Smith",
    "Maria Ivanova",
  ];

  const emails = [
    "john.doe@example.com",
    "sarah.lee@example.com",
    "ahmed.amin@example.com",
    "chen.zhang@example.com",
    "yasmin.cohen@example.com",
    "liam.oreilly@example.com",
    "marta.lopez@example.com",
    "sergey.ivanov@example.com",
    "yuki.takahashi@example.com",
    "rachel.bloom@example.com",
    "mohammed.alfarhan@example.com",
    "anika.mehta@example.com",
    "david.king@example.com",
    "javier.gonzalez@example.com",
    "sofia.rossi@example.com",
    "amir.levi@example.com",
    "emily.stone@example.com",
    "carlos.hernandez@example.com",
    "ariella.green@example.com",
    "jacob.smith@example.com",
    "maria.ivanova@example.com",
  ];

  const countries = [
    "USA",
    "Canada",
    "UK",
    "Spain",
    "Mexico",
    "Brazil",
    "France",
    "Germany",
    "China",
    "India",
    "Japan",
    "Russia",
    "Israel",
    "Argentina",
    "Pakistan",
    "Egypt",
    "Australia",
    "Italy",
    "South Africa",
    "Saudi Arabia",
    "Poland",
  ];

  const actions = ["Details"];

  function randomDate(start, end) {
    const date = new Date(
      start.getTime() + Math.random() * (end.getTime() - start.getTime()),
    );
    return date.toISOString().split("T")[0];
  }

  function randomBalance() {
    return (Math.random() * 5000).toFixed(2);
  }

  for (let i = 0; i < numEntries; i++) {
    const randomName = names[Math.floor(Math.random() * names.length)];
    const randomEmail = emails[Math.floor(Math.random() * emails.length)];
    const randomCountry =
      countries[Math.floor(Math.random() * countries.length)];
    const joinedAt = randomDate(new Date(2017, 0, 1), new Date());
    const balance = randomBalance();
    const action = actions[Math.floor(Math.random() * actions.length)];

    TableData.tableRows.push({
      bettor: randomName,
      email: randomEmail,
      country: randomCountry,
      joinedAt,
      balance,
      action,
    });
  }
}

generateRandomData(200);

export const DummyPersistentData = {
  tableHeader: [
    "Bettor",
    "Email-Mobile",
    "Country",
    "Joined At",
    "Balance",
    "Action",
  ],
  tableRows: [
    {
      bettor: "John Doe",
      email: "john.doe@example.com",
      country: "USA",
      joinedAt: "2022-01-01",
      balance: "1000.00",
      action: "Details",
    },
    {
      bettor: "Jane Smith",
      email: "jane.smith@example.com",
      country: "Canada",
      joinedAt: "2021-02-15",
      balance: "2000.00",
      action: "Details",
    },
    {
      bettor: "Ahmed Amin",
      email: "ahmed.amin@example.com",
      country: "UK",
      joinedAt: "2020-03-20",
      balance: "1500.50",
      action: "Details",
    },
    {
      bettor: "Chen Zhang",
      email: "chen.zhang@example.com",
      country: "China",
      joinedAt: "2019-04-25",
      balance: "300.75",
      action: "Details",
    },
    {
      bettor: "Yasmin Cohen",
      email: "yasmin.cohen@example.com",
      country: "Israel",
      joinedAt: "2018-05-30",
      balance: "750.30",
      action: "Details",
    },
    {
      bettor: "Liam O'Reilly",
      email: "liam.oreilly@example.com",
      country: "Ireland",
      joinedAt: "2017-06-10",
      balance: "540.20",
      action: "Details",
    },
    {
      bettor: "Marta Lopez",
      email: "marta.lopez@example.com",
      country: "Spain",
      joinedAt: "2016-07-18",
      balance: "890.40",
      action: "Details",
    },
    {
      bettor: "Sergey Ivanov",
      email: "sergey.ivanov@example.com",
      country: "Russia",
      joinedAt: "2015-08-22",
      balance: "1200.60",
      action: "Details",
    },
    {
      bettor: "Yuki Takahashi",
      email: "yuki.takahashi@example.com",
      country: "Japan",
      joinedAt: "2014-09-30",
      balance: "1100.90",
      action: "Details",
    },
    {
      bettor: "Rachel Bloom",
      email: "rachel.bloom@example.com",
      country: "USA",
      joinedAt: "2013-10-05",
      balance: "320.50",
      action: "Details",
    },
    {
      bettor: "Mohammed Al-Farhan",
      email: "mohammed.alfarhan@example.com",
      country: "Saudi Arabia",
      joinedAt: "2012-11-12",
      balance: "2000.00",
      action: "Details",
    },
    {
      bettor: "Anika Mehta",
      email: "anika.mehta@example.com",
      country: "India",
      joinedAt: "2011-12-20",
      balance: "500.25",
      action: "Details",
    },
    {
      bettor: "David King",
      email: "david.king@example.com",
      country: "UK",
      joinedAt: "2010-01-15",
      balance: "1500.75",
      action: "Details",
    },
    {
      bettor: "Javier Gonzalez",
      email: "javier.gonzalez@example.com",
      country: "Spain",
      joinedAt: "2009-02-23",
      balance: "650.00",
      action: "Details",
    },
    {
      bettor: "Sofia Rossi",
      email: "sofia.rossi@example.com",
      country: "Italy",
      joinedAt: "2008-03-30",
      balance: "780.40",
      action: "Details",
    },
    {
      bettor: "Amir Levi",
      email: "amir.levi@example.com",
      country: "Israel",
      joinedAt: "2007-04-05",
      balance: "920.30",
      action: "Details",
    },
    {
      bettor: "Emily Stone",
      email: "emily.stone@example.com",
      country: "USA",
      joinedAt: "2006-05-10",
      balance: "410.80",
      action: "Details",
    },
    {
      bettor: "Carlos Hernandez",
      email: "carlos.hernandez@example.com",
      country: "Mexico",
      joinedAt: "2005-06-15",
      balance: "570.60",
      action: "Details",
    },
    {
      bettor: "Ariella Green",
      email: "ariella.green@example.com",
      country: "Brazil",
      joinedAt: "2004-07-20",
      balance: "999.99",
      action: "Details",
    },
    {
      bettor: "Jacob Smith",
      email: "jacob.smith@example.com",
      country: "USA",
      joinedAt: "2003-08-25",
      balance: "850.10",
      action: "Details",
    },
    {
      bettor: "Maria Ivanova",
      email: "maria.ivanova@example.com",
      country: "Russia",
      joinedAt: "2002-09-30",
      balance: "300.80",
      action: "Details",
    },
    {
      bettor: "Tommy Lee",
      email: "tommy.lee@example.com",
      country: "USA",
      joinedAt: "2001-10-05",
      balance: "1250.50",
      action: "Details",
    },
    {
      bettor: "Samantha Wang",
      email: "samantha.wang@example.com",
      country: "China",
      joinedAt: "2000-11-12",
      balance: "490.90",
      action: "Details",
    },
    {
      bettor: "Omar Ali",
      email: "omar.ali@example.com",
      country: "Egypt",
      joinedAt: "1999-12-20",
      balance: "330.25",
      action: "Details",
    },
    {
      bettor: "Sophie Thompson",
      email: "sophie.thompson@example.com",
      country: "Australia",
      joinedAt: "1998-01-30",
      balance: "670.80",
      action: "Details",
    },
    {
      bettor: "Kunal Sharma",
      email: "kunal.sharma@example.com",
      country: "India",
      joinedAt: "1997-02-15",
      balance: "830.70",
      action: "Details",
    },
    {
      bettor: "Anna Peterson",
      email: "anna.peterson@example.com",
      country: "Canada",
      joinedAt: "1996-03-22",
      balance: "990.90",
      action: "Details",
    },
    {
      bettor: "George Williams",
      email: "george.williams@example.com",
      country: "UK",
      joinedAt: "1995-04-30",
      balance: "250.60",
      action: "Details",
    },
    {
      bettor: "Isabella Martinez",
      email: "isabella.martinez@example.com",
      country: "Spain",
      joinedAt: "1994-05-05",
      balance: "1230.40",
      action: "Details",
    },
    {
      bettor: "Matthew Brown",
      email: "matthew.brown@example.com",
      country: "USA",
      joinedAt: "1993-06-10",
      balance: "1450.30",
      action: "Details",
    },
    {
      bettor: "Chloe Kim",
      email: "chloe.kim@example.com",
      country: "South Korea",
      joinedAt: "1992-07-18",
      balance: "980.80",
      action: "Details",
    },
    {
      bettor: "Michael Johnson",
      email: "michael.johnson@example.com",
      country: "USA",
      joinedAt: "1991-08-25",
      balance: "1130.90",
      action: "Details",
    },
    {
      bettor: "Jessica White",
      email: "jessica.white@example.com",
      country: "Canada",
      joinedAt: "1990-09-30",
      balance: "750.10",
      action: "Details",
    },
    {
      bettor: "Joshua Thompson",
      email: "joshua.thompson@example.com",
      country: "Australia",
      joinedAt: "1989-10-05",
      balance: "380.20",
      action: "Details",
    },
    {
      bettor: "Diana Harris",
      email: "diana.harris@example.com",
      country: "UK",
      joinedAt: "1988-11-12",
      balance: "640.30",
      action: "Details",
    },
    {
      bettor: "Samuel Davis",
      email: "samuel.davis@example.com",
      country: "USA",
      joinedAt: "1987-12-20",
      balance: "540.40",
      action: "Details",
    },
    {
      bettor: "Ashley Martin",
      email: "ashley.martin@example.com",
      country: "USA",
      joinedAt: "1986-01-30",
      balance: "850.50",
      action: "Details",
    },
    {
      bettor: "Brian Wright",
      email: "brian.wright@example.com",
      country: "Canada",
      joinedAt: "1985-02-15",
      balance: "920.60",
      action: "Details",
    },
    {
      bettor: "Sarah Wilson",
      email: "sarah.wilson@example.com",
      country: "Australia",
      joinedAt: "1984-03-22",
      balance: "690.70",
      action: "Details",
    },
    {
      bettor: "Brian Brown",
      email: "brian.brown@example.com",
      country: "USA",
      joinedAt: "1983-04-30",
      balance: "450.80",
      action: "Details",
    },
    {
      bettor: "Kevin Garcia",
      email: "kevin.garcia@example.com",
      country: "Mexico",
      joinedAt: "1982-05-05",
      balance: "350.90",
      action: "Details",
    },
    {
      bettor: "Christine Lee",
      email: "christine.lee@example.com",
      country: "Canada",
      joinedAt: "1981-06-10",
      balance: "900.00",
      action: "Details",
    },
    {
      bettor: "Nina Lopez",
      email: "nina.lopez@example.com",
      country: "USA",
      joinedAt: "1980-07-18",
      balance: "780.25",
      action: "Details",
    },
    {
      bettor: "Richard Young",
      email: "richard.young@example.com",
      country: "UK",
      joinedAt: "1979-08-25",
      balance: "620.80",
      action: "Details",
    },
    {
      bettor: "Abigail Anderson",
      email: "abigail.anderson@example.com",
      country: "USA",
      joinedAt: "1978-09-30",
      balance: "530.90",
      action: "Details",
    },
    {
      bettor: "Nicholas Harris",
      email: "nicholas.harris@example.com",
      country: "Australia",
      joinedAt: "1977-10-05",
      balance: "790.60",
      action: "Details",
    },
    {
      bettor: "Olivia Hall",
      email: "olivia.hall@example.com",
      country: "Canada",
      joinedAt: "1976-11-12",
      balance: "450.70",
      action: "Details",
    },
    {
      bettor: "Hannah Robinson",
      email: "hannah.robinson@example.com",
      country: "USA",
      joinedAt: "1975-12-20",
      balance: "900.80",
      action: "Details",
    },
    {
      bettor: "David Taylor",
      email: "david.taylor@example.com",
      country: "USA",
      joinedAt: "1974-01-30",
      balance: "850.90",
      action: "Details",
    },
    {
      bettor: "Sophia Walker",
      email: "sophia.walker@example.com",
      country: "Canada",
      joinedAt: "1973-02-15",
      balance: "690.10",
      action: "Details",
    },
    {
      bettor: "Lucas Miller",
      email: "lucas.miller@example.com",
      country: "USA",
      joinedAt: "1972-03-22",
      balance: "300.50",
      action: "Details",
    },
    {
      bettor: "Mia Wilson",
      email: "mia.wilson@example.com",
      country: "Australia",
      joinedAt: "1971-04-30",
      balance: "620.40",
      action: "Details",
    },
    {
      bettor: "Ella Martinez",
      email: "ella.martinez@example.com",
      country: "Canada",
      joinedAt: "1970-05-05",
      balance: "1500.60",
      action: "Details",
    },
    {
      bettor: "Ethan Brown",
      email: "ethan.brown@example.com",
      country: "USA",
      joinedAt: "1969-06-10",
      balance: "550.70",
      action: "Details",
    },
    {
      bettor: "Grace Johnson",
      email: "grace.johnson@example.com",
      country: "UK",
      joinedAt: "1968-07-18",
      balance: "750.80",
      action: "Details",
    },
    {
      bettor: "Logan Smith",
      email: "logan.smith@example.com",
      country: "USA",
      joinedAt: "1967-08-25",
      balance: "900.90",
      action: "Details",
    },
    {
      bettor: "Victoria Rodriguez",
      email: "victoria.rodriguez@example.com",
      country: "Canada",
      joinedAt: "1966-09-30",
      balance: "150.30",
      action: "Details",
    },
    {
      bettor: "Alexander Harris",
      email: "alexander.harris@example.com",
      country: "USA",
      joinedAt: "1965-10-05",
      balance: "350.40",
      action: "Details",
    },
    {
      bettor: "Abigail Thomas",
      email: "abigail.thomas@example.com",
      country: "Australia",
      joinedAt: "1964-11-12",
      balance: "600.50",
      action: "Details",
    },
    {
      bettor: "Daniel Lewis",
      email: "daniel.lewis@example.com",
      country: "Canada",
      joinedAt: "1963-12-20",
      balance: "450.60",
      action: "Details",
    },
    {
      bettor: "Mason Clark",
      email: "mason.clark@example.com",
      country: "USA",
      joinedAt: "1962-01-30",
      balance: "300.70",
      action: "Details",
    },
    {
      bettor: "Sophia Walker",
      email: "sophia.walker@example.com",
      country: "UK",
      joinedAt: "1961-02-15",
      balance: "800.80",
      action: "Details",
    },
    {
      bettor: "James Turner",
      email: "james.turner@example.com",
      country: "Canada",
      joinedAt: "1960-03-22",
      balance: "650.90",
      action: "Details",
    },
    {
      bettor: "Isabella Phillips",
      email: "isabella.phillips@example.com",
      country: "USA",
      joinedAt: "1959-04-30",
      balance: "700.10",
      action: "Details",
    },
    {
      bettor: "Oliver Scott",
      email: "oliver.scott@example.com",
      country: "Australia",
      joinedAt: "1958-05-05",
      balance: "800.20",
      action: "Details",
    },
    {
      bettor: "Ava Robinson",
      email: "ava.robinson@example.com",
      country: "Canada",
      joinedAt: "1957-06-10",
      balance: "400.30",
      action: "Details",
    },
    {
      bettor: "Charlotte Martinez",
      email: "charlotte.martinez@example.com",
      country: "USA",
      joinedAt: "1956-07-18",
      balance: "950.40",
      action: "Details",
    },
    {
      bettor: "Jack Anderson",
      email: "jack.anderson@example.com",
      country: "UK",
      joinedAt: "1955-08-25",
      balance: "500.50",
      action: "Details",
    },
    {
      bettor: "Ella Lee",
      email: "ella.lee@example.com",
      country: "Canada",
      joinedAt: "1954-09-30",
      balance: "700.60",
      action: "Details",
    },
    {
      bettor: "Henry Harris",
      email: "henry.harris@example.com",
      country: "USA",
      joinedAt: "1953-10-05",
      balance: "650.70",
      action: "Details",
    },
    {
      bettor: "Emily Nelson",
      email: "emily.nelson@example.com",
      country: "Australia",
      joinedAt: "1952-11-12",
      balance: "780.80",
      action: "Details",
    },
    {
      bettor: "William Baker",
      email: "william.baker@example.com",
      country: "Canada",
      joinedAt: "1951-12-20",
      balance: "400.90",
      action: "Details",
    },
    {
      bettor: "Olivia Hill",
      email: "olivia.hill@example.com",
      country: "USA",
      joinedAt: "1950-01-30",
      balance: "320.00",
      action: "Details",
    },
    {
      bettor: "Matthew Lewis",
      email: "matthew.lewis@example.com",
      country: "UK",
      joinedAt: "1949-02-15",
      balance: "540.10",
      action: "Details",
    },
    {
      bettor: "Ava Young",
      email: "ava.young@example.com",
      country: "Canada",
      joinedAt: "1948-03-22",
      balance: "610.20",
      action: "Details",
    },
    {
      bettor: "Lucas Scott",
      email: "lucas.scott@example.com",
      country: "USA",
      joinedAt: "1947-04-30",
      balance: "430.30",
      action: "Details",
    },
    {
      bettor: "Scarlett White",
      email: "scarlett.white@example.com",
      country: "Australia",
      joinedAt: "1946-05-05",
      balance: "320.40",
      action: "Details",
    },
    {
      bettor: "Sebastian Adams",
      email: "sebastian.adams@example.com",
      country: "Canada",
      joinedAt: "1945-06-10",
      balance: "780.50",
      action: "Details",
    },
    {
      bettor: "Madison Kelly",
      email: "madison.kelly@example.com",
      country: "USA",
      joinedAt: "1944-07-18",
      balance: "890.60",
      action: "Details",
    },
    {
      bettor: "Joseph Green",
      email: "joseph.green@example.com",
      country: "UK",
      joinedAt: "1943-08-25",
      balance: "610.70",
      action: "Details",
    },
    {
      bettor: "Harper Hall",
      email: "harper.hall@example.com",
      country: "Canada",
      joinedAt: "1942-09-30",
      balance: "890.80",
      action: "Details",
    },
    {
      bettor: "Anthony Harris",
      email: "anthony.harris@example.com",
      country: "USA",
      joinedAt: "1941-10-05",
      balance: "760.90",
      action: "Details",
    },
    {
      bettor: "Natalie Lee",
      email: "natalie.lee@example.com",
      country: "Australia",
      joinedAt: "1940-11-12",
      balance: "530.00",
      action: "Details",
    },
  ],
};

export const ManageCategoriesData = {
  headers: [
    { label: "Name", key: "name" },
    { label: "Slug", key: "slug" },
    { label: "Icon", key: "icon" },
    { label: "Leagues", key: "leagues" },
    { label: "Teams", key: "teams" },
    { label: "Status", key: "status" },
    { label: "Action", key: "actions" },
  ],
  rows: [
    {
      name: "Dart",
      slug: "dart",
      icon: "🎯",
      leagues: 4,
      teams: 6,
      status: "Enabled",
      actions: ["Edit", "Disable"],
    },
    {
      name: "Baseball",
      slug: "baseball",
      icon: "⚾",
      leagues: 14,
      teams: 11,
      status: "Enabled",
      actions: ["Edit", "Disable"],
    },
    {
      name: "Badminton",
      slug: "badminton",
      icon: "🏸",
      leagues: 11,
      teams: 11,
      status: "Enabled",
      actions: ["Edit", "Disable"],
    },
    {
      name: "Boxing",
      slug: "boxing",
      icon: "🥊",
      leagues: 8,
      teams: 11,
      status: "Enabled",
      actions: ["Edit", "Disable"],
    },
    {
      name: "Handball",
      slug: "handball",
      icon: "⏱️",
      leagues: 4,
      teams: 12,
      status: "Enabled",
      actions: ["Edit", "Disable"],
    },
    {
      name: "Golf",
      slug: "golf",
      icon: "🏌️",
      leagues: 5,
      teams: 12,
      status: "Enabled",
      actions: ["Edit", "Disable"],
    },
    {
      name: "Rugby",
      slug: "rugby",
      icon: "🏉",
      leagues: 14,
      teams: 12,
      status: "Enabled",
      actions: ["Edit", "Disable"],
    },
    {
      name: "Volleyball",
      slug: "volleyball",
      icon: "🏐",
      leagues: 1,
      teams: 14,
      status: "Enabled",
      actions: ["Edit", "Disable"],
    },
    {
      name: "Tennis",
      slug: "tennis",
      icon: "🎾",
      leagues: 20,
      teams: 14,
      status: "Enabled",
      actions: ["Edit", "Disable"],
    },
    {
      name: "Hockey",
      slug: "hockey",
      icon: "🏒",
      leagues: 18,
      teams: 15,
      status: "Enabled",
      actions: ["Edit", "Disable"],
    },
    {
      name: "Basketball",
      slug: "basketball",
      icon: "🏀",
      leagues: 16,
      teams: 20,
      status: "Enabled",
      actions: ["Edit", "Disable"],
    },
    {
      name: "Cricket",
      slug: "cricket",
      icon: "🏏",
      leagues: 4,
      teams: 34,
      status: "Enabled",
      actions: ["Edit", "Disable"],
    },
    {
      name: "Soccer",
      slug: "soccer",
      icon: "⚽",
      leagues: 25,
      teams: 40,
      status: "Enabled",
      actions: ["Edit", "Disable"],
    },
    {
      name: "Swimming",
      slug: "swimming",
      icon: "🏊",
      leagues: 10,
      teams: 6,
      status: "Enabled",
      actions: ["Edit", "Disable"],
    },
    {
      name: "Archery",
      slug: "archery",
      icon: "🏹",
      leagues: 3,
      teams: 2,
      status: "Disabled",
      actions: ["Edit", "Enable"],
    },
    {
      name: "Table Tennis",
      slug: "table-tennis",
      icon: "🏓",
      leagues: 5,
      teams: 7,
      status: "Enabled",
      actions: ["Edit", "Disable"],
    },
    {
      name: "Cycling",
      slug: "cycling",
      icon: "🚴",
      leagues: 6,
      teams: 8,
      status: "Disabled",
      actions: ["Edit", "Enable"],
    },
    {
      name: "Snooker",
      slug: "snooker",
      icon: "🎱",
      leagues: 4,
      teams: 9,
      status: "Enabled",
      actions: ["Edit", "Disable"],
    },
    {
      name: "Skating",
      slug: "skating",
      icon: "⛸️",
      leagues: 2,
      teams: 5,
      status: "Disabled",
      actions: ["Edit", "Enable"],
    },
  ],
};

export const RunningGamesData = {
  tableHeader: [
    "Title",
    "League | Category",
    "Game Starts From",
    "Bet Starts From",
    "Bet Ends At",
    "Markets",
    "Status",
    "Action",
  ],
  tableRows: [
    {
      team1: { name: "MOBA", icon: "🥊" },
      team2: { name: "MIAC", icon: "🥊" },
      league: { name: "PBWTF", category: "Boxing" },
      gameStartsFrom: "30 Oct, 2023 05:59 AM",
      betStartsFrom: "29 Oct, 2023 05:59 PM",
      betEndsAt: "30 Oct, 2024, 05:59 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "COBJ", icon: "🏒" },
      team2: { name: "TOML", icon: "🏒" },
      league: { name: "HC", category: "Hockey" },
      gameStartsFrom: "24 Mar, 2024 10:19 AM",
      betStartsFrom: "23 Mar, 2024 10:19 PM",
      betEndsAt: "24 Mar, 2025, 10:19 AM",
      markets: 2,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
    {
      team1: { name: "MITW", icon: "⚾" },
      team2: { name: "STLC", icon: "⚾" },
      league: { name: "FSL", category: "Baseball" },
      gameStartsFrom: "05 Mar, 2024 03:01 AM",
      betStartsFrom: "04 Mar, 2024 03:01 PM",
      betEndsAt: "05 Mar, 2025, 03:01 AM",
      markets: 1,
      status: "Enabled",
      action: ["Edit", "Disable", "Markets"],
    },
  ],
};

export const ManageBetsData = {
  tableHeader: [
    "Bet Number",
    "Type",
    "Stake Amount",
    "Return",
    "Status",
    "Action",
  ],
  tableRows: [
    {
      betNumber: "2OUYT8RP",
      user: "@serguy1984",
      type: "Multi",
      stakeAmount: "$10,000.00",
      return: "$14,829,526.44",
      status: "Pending",
      action: "Detail",
    },
    {
      betNumber: "QU7CGW5G",
      user: "@joker888",
      type: "Single",
      stakeAmount: "$5.00",
      return: "$7.00",
      status: "Pending",
      action: "Detail",
    },
    {
      betNumber: "KZ91LKLD",
      user: "@joker888",
      type: "Single",
      stakeAmount: "$15.00",
      return: "$41.25",
      status: "Pending",
      action: "Detail",
    },
    {
      betNumber: "1SQQ5ECQ",
      user: "@testuser",
      type: "Single",
      stakeAmount: "$6.00",
      return: "$13.20",
      status: "Pending",
      action: "Detail",
    },
    {
      betNumber: "X22J0IFN",
      user: "@0ipukhrajdhamu@gmail.com",
      type: "Single",
      stakeAmount: "$20.00",
      return: "$32.40",
      status: "Pending",
      action: "Detail",
    },

    {
      betNumber: "KZ91LKLD",
      user: "@joker888",
      type: "Single",
      stakeAmount: "$15.00",
      return: "$41.25",
      status: "Pending",
      action: "Detail",
    },
    {
      betNumber: "LUHBQS8D",
      user: "@testuser",
      type: "Single",
      stakeAmount: "$6.00",
      return: "$8.70",
      status: "Pending",
      action: "Detail",
    },
    {
      betNumber: "1SQQ5ECQ",
      user: "@testuser",
      type: "Single",
      stakeAmount: "$6.00",
      return: "$13.20",
      status: "Pending",
      action: "Detail",
    },
    {
      betNumber: "2OPILOFI",
      user: "@testuser",
      type: "Single",
      stakeAmount: "$6.00",
      return: "$9.72",
      status: "Pending",
      action: "Detail",
    },
    {
      betNumber: "KZ91LKLD",
      user: "@joker888",
      type: "Single",
      stakeAmount: "$15.00",
      return: "$41.25",
      status: "Pending",
      action: "Detail",
    },
    {
      betNumber: "SWMWHPD7",
      user: "@testuser",
      type: "Single",
      stakeAmount: "$6.00",
      return: "$19.20",
      status: "Pending",
      action: "Detail",
    },
    {
      betNumber: "1SQQ5ECQ",
      user: "@testuser",
      type: "Single",
      stakeAmount: "$6.00",
      return: "$13.20",
      status: "Pending",
      action: "Detail",
    },
    {
      betNumber: "9EX2J8C8",
      user: "@testuser",
      type: "Single",
      stakeAmount: "$6.00",
      return: "$19.20",
      status: "Pending",
      action: "Detail",
    },
    {
      betNumber: "KZ91LKLD",
      user: "@joker888",
      type: "Single",
      stakeAmount: "$15.00",
      return: "$41.25",
      status: "Pending",
      action: "Detail",
    },
    {
      betNumber: "1SQQ5ECQ",
      user: "@testuser",
      type: "Single",
      stakeAmount: "$6.00",
      return: "$13.20",
      status: "Pending",
      action: "Detail",
    },
    {
      betNumber: "KZ91LKLD",
      user: "@joker888",
      type: "Single",
      stakeAmount: "$15.00",
      return: "$41.25",
      status: "Pending",
      action: "Detail",
    },
    {
      betNumber: "3GKD8ATH",
      user: "@testuser",
      type: "Single",
      stakeAmount: "$6.00",
      return: "$12.60",
      status: "Pending",
      action: "Detail",
    },
  ],
};

export const DepositsData = {
  tableHeader: [
    "Gateway | Transaction",
    "Initiated",
    "User",
    "Amount",
    "Conversion",
    "Status",
    "Action",
  ],
  tableRows: [
    {
      transaction: "Bank Transfer",
      transactionID: "DH5VD8DSQM6A",
      initiated: "2024-10-17 10:36 PM",
      timeAgo: "4 days ago",
      userName: "user1",
      userId: "@afffkuh75",
      lastAmount: 50.0,
      addAmount: 5.5,
      totalAmount: 55.5,
      conversion: "$1.00 = 1.00 USD",
      status: "Pending",
      action: "Details",
    },
    {
      transaction: "Bank Transfer",
      transactionID: "MDM5A5A474MFG",
      initiated: "2024-10-15 08:58 PM",
      timeAgo: "6 days ago",
      userName: "user2",
      userId: "@Hgghjg5",
      lastAmount: 10000.0,
      addAmount: 105.0,
      totalAmount: 10105.0,
      conversion: "$1.00 = 1.00 USD",
      status: "Pending",
      action: "Details",
    },
    {
      transaction: "Bank Transfer",
      transactionID: "TVIVRMJ2QHN1",
      initiated: "2024-10-12 02:00 AM",
      timeAgo: "1 week ago",
      userName: "user3",
      userId: "@Rmyyy123",
      lastAmount: 50.0,
      addAmount: 5.5,
      totalAmount: 55.5,
      conversion: "$1.00 = 1.00 USD",
      status: "Pending",
      action: "Details",
    },
    {
      transaction: "Bank Transfer",
      transactionID: "QPDEVBNFVCVH",
      initiated: "2024-10-09 04:37 PM",
      timeAgo: "1 week ago",
      userName: "user4",
      userId: "@Faliipikin",
      lastAmount: 20.0,
      addAmount: 5.2,
      totalAmount: 25.2,
      conversion: "$1.00 = 1.00 USD",
      status: "Pending",
      action: "Details",
    },
    {
      transaction: "Bank Transfer",
      transactionID: "66G9RMF4P33J",
      initiated: "2024-10-02 09:03 PM",
      timeAgo: "2 weeks ago",
      userName: "user5",
      userId: "@bokshigonj",
      lastAmount: 50.0,
      addAmount: 5.5,
      totalAmount: 55.5,
      conversion: "$1.00 = 1.00 USD",
      status: "Pending",
      action: "Details",
    },
    {
      transaction: "Bank Transfer",
      transactionID: "C6LP78U3WIIU",
      initiated: "2024-10-02 08:53 PM",
      timeAgo: "2 weeks ago",
      userName: "user6",
      userId: "@FDEF755",
      lastAmount: 44.0,
      addAmount: 5.44,
      totalAmount: 49.44,
      conversion: "49.44 USD",
      status: "Pending",
      action: "Details",
    },
    {
      transaction: "Bank Transfer",
      transactionID: "BONVIBA47GBC",
      initiated: "2024-09-29 06:20 PM",
      timeAgo: "3 weeks ago",
      userName: "user7",
      userId: "@0ipukhrajdhamu",
      lastAmount: 1000.0,
      addAmount: 15.0,
      totalAmount: 1015.0,
      conversion: "$1.00 = 1.00 USD",
      status: "Pending",
      action: "Details",
    },
  ],
};

export const WithdrawlsData = {
  tableHeader: [
    "Gateway | Transaction",
    "Initiated",
    "User",
    "Amount",
    "Conversion",
    "Status",
    "Action",
  ],
  tableRows: [
    {
      transaction: "Bank Transfer",
      transactionID: "DH5VD8DSQM6A",
      initiated: "2024-10-17 10:36 PM",
      timeAgo: "4 days ago",
      userName: "user1",
      userId: "@afffkuh75",
      lastAmount: 50.0, // Numeric last amount
      subtractAmount: 5.5, // Numeric subtract amount
      totalAmount: 44.5, // Total amount after subtraction
      conversion: "$1.00 = 1.00 USD",
      status: "Pending",
      action: "Details",
    },
    {
      transaction: "Bank Transfer",
      transactionID: "MDM5A5A474MFG",
      initiated: "2024-10-15 08:58 PM",
      timeAgo: "6 days ago",
      userName: "user2",
      userId: "@Hgghjg5",
      lastAmount: 10000.0,
      subtractAmount: 105.0,
      totalAmount: 9895.0,
      conversion: "$1.00 = 1.00 USD",
      status: "Pending",
      action: "Details",
    },
    {
      transaction: "Bank Transfer",
      transactionID: "TVIVRMJ2QHN1",
      initiated: "2024-10-12 02:00 AM",
      timeAgo: "1 week ago",
      userName: "user3",
      userId: "@Rmyyy123",
      lastAmount: 50.0,
      subtractAmount: 5.5,
      totalAmount: 44.5,
      conversion: "$1.00 = 1.00 USD",
      status: "Pending",
      action: "Details",
    },
    {
      transaction: "Bank Transfer",
      transactionID: "QPDEVBNFVCVH",
      initiated: "2024-10-09 04:37 PM",
      timeAgo: "1 week ago",
      userName: "user4",
      userId: "@Faliipikin",
      lastAmount: 20.0,
      subtractAmount: 5.2,
      totalAmount: 14.8,
      conversion: "$1.00 = 1.00 USD",
      status: "Pending",
      action: "Details",
    },
    {
      transaction: "Bank Transfer",
      transactionID: "66G9RMF4P33J",
      initiated: "2024-10-02 09:03 PM",
      timeAgo: "2 weeks ago",
      userName: "user5",
      userId: "@bokshigonj",
      lastAmount: 50.0,
      subtractAmount: 5.5,
      totalAmount: 44.5,
      conversion: "$1.00 = 1.00 USD",
      status: "Pending",
      action: "Details",
    },
    {
      transaction: "Bank Transfer",
      transactionID: "C6LP78U3WIIU",
      initiated: "2024-10-02 08:53 PM",
      timeAgo: "2 weeks ago",
      userName: "user6",
      userId: "@FDEF755",
      lastAmount: 44.0,
      subtractAmount: 5.44,
      totalAmount: 38.56,
      conversion: "$1.00 = 1.00 USD",
      status: "Pending",
      action: "Details",
    },
    {
      transaction: "Bank Transfer",
      transactionID: "BONVIBA47GBC",
      initiated: "2024-09-29 06:20 PM",
      timeAgo: "3 weeks ago",
      userName: "user7",
      userId: "@0ipukhrajdhamu",
      lastAmount: 1000.0,
      subtractAmount: 15.0,
      totalAmount: 985.0,
      conversion: "$1.00 = 1.00 USD",
      status: "Pending",
      action: "Details",
    },
  ],
};

export const ManageTicketsData = {
  tableHeader: [
    "Subject",
    "Submitted By",
    "Status",
    "Priority",
    "Last Reply",
    "Action",
  ],
  tableRows: [
    {
      ticketId: "428996",
      subject: "subject",
      submittedBy: "李勇南",
      status: "Open",
      priority: "High",
      lastReply: "2 months ago",
      action: "Detail",
    },
    {
      ticketId: "964883",
      subject: "sadasdadasdasda",
      submittedBy: "Jay Justalero",
      status: "Open",
      priority: "High",
      lastReply: "3 months ago",
      action: "Detail",
    },
    {
      ticketId: "649061",
      subject: "qwdqwdqwd",
      submittedBy: "Vishal Khan",
      status: "Open",
      priority: "High",
      lastReply: "6 months ago",
      action: "Detail",
    },
    {
      ticketId: "964884",
      subject: "Buhari and Atiku",
      submittedBy: "alabi babatunde",
      status: "Open",
      priority: "High",
      lastReply: "8 months ago",
      action: "Detail",
    },
    {
      ticketId: "620571",
      subject: "Bet Matters",
      submittedBy: "alabi babatunde",
      status: "Open",
      priority: "High",
      lastReply: "8 months ago",
      action: "Detail",
    },
    {
      ticketId: "27116674",
      subject: "Est elit eos corpo",
      submittedBy: "Kelly Francis",
      status: "Open",
      priority: "Medium",
      lastReply: "8 months ago",
      action: "Detail",
    },
    {
      ticketId: "32054979",
      subject: "Quo aut nulla cupidi",
      submittedBy: "Nola Mack",
      status: "Open",
      priority: "Medium",
      lastReply: "8 months ago",
      action: "Detail",
    },
    {
      ticketId: "39103624",
      subject: "Aut quis excepturi o",
      submittedBy: "Nathan Madden",
      status: "Customer Reply",
      priority: "Medium",
      lastReply: "8 months ago",
      action: "Detail",
    },
    {
      ticketId: "29225439",
      subject: "Rerum veniam fugiat",
      submittedBy: "Wilma Mcmahon",
      status: "Open",
      priority: "Medium",
      lastReply: "8 months ago",
      action: "Detail",
    },
    {
      ticketId: "01770930",
      subject: "Error commodo pariat",
      submittedBy: "Elmo Knight",
      status: "Open",
      priority: "Medium",
      lastReply: "8 months ago",
      action: "Detail",
    },
    {
      ticketId: "90537917",
      subject: "Cillum excepteur per",
      submittedBy: "Kirby Skinner",
      status: "Customer Reply",
      priority: "Medium",
      lastReply: "8 months ago",
      action: "Detail",
    },
    {
      ticketId: "803622",
      subject: "sdafsadf",
      submittedBy: "Vishal Khan",
      status: "Open",
      priority: "High",
      lastReply: "9 months ago",
      action: "Detail",
    },
    {
      ticketId: "859947",
      subject: "ghjkl",
      submittedBy: "Vishal Khan",
      status: "Open",
      priority: "High",
      lastReply: "10 months ago",
      action: "Detail",
    },
    {
      ticketId: "475584",
      subject: "test subject",
      submittedBy: "Vishal Khan",
      status: "Open",
      priority: "High",
      lastReply: "10 months ago",
      action: "Detail",
    },
    {
      ticketId: "602474",
      subject: "Ut voluptate blandit",
      submittedBy: "John Doe",
      status: "Customer Reply",
      priority: "High",
      lastReply: "6 months ago",
      action: "Detail",
    },
  ],
};

export const PendingOutcomesData = {
  tableHeader: ["Market", "Match", "Bet End Time", "BetPlaced", "Action"],
  tableRows: [
    {
      market: "1. Total Match Points (Odd/Even)",
      match: { team1: "CAAL", team2: "CANO" },
      betEndTime: "2024-11-10 04:47 PM",
      timeLeft: "2 weeks from now",
      betPlaced: 2,
      action: ["Select Outcome", "Refund Bet", "Bets"],
    },
    {
      market: "2. 1st Half Total Points",
      match: { team1: "PH76", team2: "SLG" },
      betEndTime: "2025-02-17 12:44 PM",
      timeLeft: "3 months from now",
      betPlaced: 1,
      action: ["Select Outcome", "Refund Bet", "Bets"],
    },
    {
      market: "3. 1st Half Odd or Even",
      match: { team1: "MIBU", team2: "BOC" },
      betEndTime: "2024-07-22 02:53 PM",
      timeLeft: "2 months ago",
      betPlaced: 1,
      action: ["Select Outcome", "Refund Bet", "Bets"],
    },
    {
      market: "4. 1st Half Total Points",
      match: { team1: "MIBU", team2: "BOC" },
      betEndTime: "2024-07-22 02:53 PM",
      timeLeft: "2 months ago",
      betPlaced: 2,
      action: ["Select Outcome", "Refund Bet", "Bets"],
    },
    {
      market: "5. 1st Innings Total",
      match: { team1: "NAM", team2: "AFG" },
      betEndTime: "2024-11-11 12:18 PM",
      timeLeft: "3 weeks from now",
      betPlaced: 3,
      action: ["Select Outcome", "Refund Bet", "Bets"],
    },
    {
      market: "6. At least One Batsman Will Score Century",
      match: { team1: "NAM", team2: "AFG" },
      betEndTime: "2024-11-11 12:18 PM",
      timeLeft: "3 weeks from now",
      betPlaced: 1,
      action: ["Select Outcome", "Refund Bet", "Bets"],
    },
    {
      market: "7. 1st Ball Wicket in 1st Innings",
      match: { team1: "NAM", team2: "AFG" },
      betEndTime: "2024-11-11 12:18 PM",
      timeLeft: "3 weeks from now",
      betPlaced: 1,
      action: ["Select Outcome", "Refund Bet", "Bets"],
    },
    {
      market: "8. 1st Innings Total",
      match: { team1: "ENG", team2: "CV" },
      betEndTime: "2024-09-13 02:35 PM",
      timeLeft: "1 month ago",
      betPlaced: 4,
      action: ["Select Outcome", "Refund Bet", "Bets"],
    },
    {
      market: "9. At least One Batsman Will Score Century",
      match: { team1: "ENG", team2: "CV" },
      betEndTime: "2024-09-13 02:35 PM",
      timeLeft: "1 month ago",
      betPlaced: 1,
      action: ["Select Outcome", "Refund Bet", "Bets"],
    },
  ],
};
